<<<<<<< HEAD
# DeepSource configuration file
# Learn how to configure: https://docs.deepsource.com/docs/configuration
version = 1
exclude_patterns = ["node_modules", "bower_components", "out", "bin", "build", "dist"]
test_patterns = ["**/__tests__/**", "**/*.spec.ts", "**/*.spec.js", "**/*.test.ts", "**/*.test.js"]

[[analyzers]]
  name = "php"
  enabled = true

[[analyzers]]
  name = "javascript"
  enabled = true
=======
version = 1

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["bootstrap"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["jest"]
>>>>>>> refs/remotes/origin/main
